### ISSUE TITLE
modbus : discover all the device Master and slave and generating a json file with all the devices and data model (parameters supporting)

### ISSUE THREAD

**Issue by yboujraf** [LukeL99/simple-modbus#12]
Dear @LukeL99 

I am working on a proprietary protocol translator from /to modbus.

I need to discover all the modbus device master/slave and get the list of parameters they are able to support (finally the data model) for each devic discovered.

It's our data model for one parameter it could be string, boolean, real, integer, ....

```
{

                    "number": 0,
                    "identifier": "ParameTypeInteger",
                    "description": "",
                    "value": 0,
                    "minimum": -4096,
                    "maximum": 0,
                    "access": "readWrite",
                    "format": "%8.2f°",
                    "enumeration": "",
                    "factor": 32,
                    "isOnline": true,
                    "formula": "1*\n1/",
                    "default": -1024,
                    "type": "integer"
                }               {

                    "number": 1,
                    "identifier": "ParameTypeReal",
                    "description": "",
                    "value": 0,
                    "minimum": 0,
                    "maximum": 4096,
                    "access": "readWrite",
                    "format": "%8.2f°",
                    "enumeration": "",
                    "factor": 1,
                    "isOnline": true,
                    "formula": "10*\n10/",
                    "default": 100,
                    "type": "real"
                },
                {
                    "number": 2,
                    "identifier": "ParameTypeString",
                    "description": "",
                    "value": "text",
                    "access": "readWrite",
                    "enumeration": "Yes\nNo\nOk",
                    "isOnline": true,
                    "default": "default",
                    "type": "string"
                },
                {
                    "number": 3,
                    "identifier": "ParameTypeEnumeration",
                    "description": "",
                    "value": 0,
                    "access": "readWrite",
                    "enumeration": "Line\nMic+48V\nMic",
                    "isOnline": true,
                    "default": 0,
                    "type": "enum"
                },
                {
                    "number": 4,
                    "identifier": "ParameTypeBoolean",
                    "description": "",
                    "value": true,
                    "access": "readWrite",
                    "isOnline": true,
                    "default": false,
                    "type": "boolean"
                }
```

How we could do with you code to generate a json file with all the devices ?

Best regards
Youssef

**Comment by yboujraf** [comment]
Dear @LukeL99 

Me i have done 2.5 the roundtrip of the world in 2019 North south east and west.

You are a lucky guy.

Yes i am still working on it.
To be honest i am not knowing very well the Modbus protocol and hope you could help me to give the correct direction to support my use case.

Best regards
Youssef

**Comment by yboujraf** [comment]
Dear @LukeL99 

I have moxa IO device and could enable modbus as client/server TCP/UDP/Serial

I need support to test your library with the device then we could see if we could make a function :

- GetDirectory
++ List all the modbus devices available on the network or gateway
- GetDataModel
++ For each device, to expand the list of parameters
++ export in json the DataModel
```
{

                    "number": 1,
                    "identifier": "ParameTypeReal",
                    "description": "",
                    "value": 0,
                    "minimum": 0,
                    "maximum": 4096,
                    "access": "readWrite",
                    "format": "%8.2f°",
                    "enumeration": "",
                    "factor": 1,
                    "isOnline": true,
                    "formula": "10*\n10/",
                    "default": 100,
                    "type": "real"
                }
```


- SetValue
++ To set any parameters respecting type, min, max, ...

- GetValue
++ To Get any parameters respecting type, min, max, ...

- To Subscribe to any event
++ changevalue
...

Regarding pcap capture, please share the procedure to capture then I will do it and share to it some devices.

Best Regards,
Youssef

**Comment by LukeL99** [comment]
Hey Youssef,

There is no auto discovery built into the Modbus protocol that I'm aware of. It's a very simple protocol for writing to and reading from various memory locations on devices that are known. The data storage location is defined by the user of the system, and there's no way to enumerate know what is in the register through modbus itself.

For instance - if I'm designing a PLC application, I could put temperature, a counter, or a voltage into register 1. It's up to the application consuming the data to know the IP address, register location, and request the data from register 1 and know how to process it. There's no way to get the data you're requesting that I know of.

This library can do SetValue and GetValue, as you have them defined above. The way to subscribe to events would be to poll the register of a given value at a set time period, and compare that to the last value. Otherwise your only option would be to update the PLC to push data to a server acting as a modbus slave, something that is not implemented in this library at this time.

**Comment by LukeL99** [comment]
Hey Youssef,

Modbus doesn't support discovery, unfortunately. You're going to have to define your register locations, and model this data yourself. This library supports acting as a server (slave) only at the moment. In the future, when I have time, I want to extend it to have a client (master) as well.

With modbus, you have to know the register location and format of the data you're trying to access. That data model is defined by the implementer of the system. You can store data in any format in the registers of a PLC. I don't think there's any way to get the data you are requesting above, because the PLC doesn't have a concept of most of the fields you've specified.

**Comment by yboujraf** [comment]
Dear Luke,

Thanks for the feedback.

I will find first a Modbus device and test it.

Best regards
